name: winners
description: "Church Management System"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11
  flutter_slidable: ^3.1.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  intro_screen_onboarding_flutter: ^1.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  youtube_api: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/papa.png
  branding: assets/images/echotronic_light.png
  color_dark: "#121212"
  image_dark: assets/images/papa.png
  branding_dark: assets/images/echotronic_dark.png

  android_12:
    image: assets/images/papa.png
    icon_background_color: "#000000"
    image_dark: assets/images/papa.png
    icon_background_color_dark: "#121212"

  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
